# Generated by Django 5.0.2 on 2024-03-02 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='next_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_test', to='my_tests.test'),
        ),
    ]
