# Generated by Django 5.0.2 on 2024-03-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0003_test_next_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='next_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_test', to='my_tests.test'),
        ),
    ]
